# Generated by Django 3.1.3 on 2021-01-21 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210121_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powermeasurements',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 13, 49, 16, 51751, tzinfo=utc), editable=False),
        ),
    ]
