# Generated by Django 3.1.3 on 2021-01-21 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210121_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powermeasurements',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
